export default {
	name: "Invoice",
	generic: true,
	title: "Invoice",
	titleP: "Invoices",
	url: "/invoices",
	disableCreate: true,
	disableEdit: true,
	fields: [
		{
			type: "text",
			inputType: "text",
			name: "id",
			tableName: "id",
			label: "ID",
			placeholder: "ID",
			inTable: true,
		},
		{
			type: "text",
			inputType: "text",
			name: "customer",
			tableName: "customer",
			label: "Customer",
			placeholder: "Customer",
			inTable: true,
		},
		{
			type: "text",
			inputType: "text",
			name: "email",
			tableName: "email",
			label: "Email",
			placeholder: "Email",
			inTable: true,
		},
		{
			type: "text",
			inputType: "text",
			name: "total",
			tableName: "total",
			label: "Total",
			placeholder: "Total",
			inTable: true,
			format: "currency",
		},
	],
};
