export default {
	name: "Organizer",
	generic: true,
	title: "Event Organizer",
	titleP: "Event Organizers",
	url: "/organizers",
	disableCreate: false,
	disableEdit: false,
	icon: "team",
	fields: [
		{
			type: "text",
			inputType: "text",
			name: "name",
			tableName: "name",
			label: "Name",
			placeholder: "Name",
			inTable: true,
			required: true,
		},
		{
			type: "text",
			inputType: "email",
			name: "email",
			tableName: "email",
			label: "Email",
			placeholder: "Email",
			inTable: true,
			required: true,
		},
		{
			type: "tel",
			inputType: "tel",
			name: "phone",
			tableName: "phone",
			label: "Phone",
			placeholder: "Phone",
			inTable: true,
			required: true
		},
		{
			type: "select",
			name: "nationality",
			tableName: "nationality",
			label: "Nationality",
			url: "/public/get-country",
			options: [],
			placeholder: "Select Nationality",
			loadExternal: true,
			isPublic: true,
		},
		{
			type: "select",
			name: "country",
			tableName: "country",
			label: "Country",
			url: "/public/get-country",
			options: [],
			placeholder: "Select Country",
			loadExternal: true,
			isPublic: true,
		},
		{
			type: "text",
			inputType: "text",
			name: "state",
			tableName: "state",
			label: "State",
			placeholder: "State",
		},
		{
			type: "text",
			inputType: "text",
			name: "city",
			tableName: "city",
			label: "City",
			placeholder: "City",
		},
		{
			type: "text",
			inputType: "text",
			name: "street",
			tableName: "street",
			label: "Street",
			placeholder: "Street",
		},
		{
			type: "text",
			inputType: "text",
			name: "zipCode",
			tableName: "zipCode",
			label: "Zip Code",
			placeholder: "Zip Code",
		},
		{
			type: "text",
			inputType: "text",
			name: "companyName",
			tableName: "companyName",
			label: "Company Name (If Company)",
			placeholder: "Company Name (If Company)",
		},
		{
			type: "tel",
			inputType: "tel",
			name: "companyPhone",
			tableName: "companyPhone",
			label: "Company Phone",
			placeholder: "Company Phone",
		},
		{
			type: "text",
			inputType: "url",
			name: "website",
			tableName: "website",
			label: "Website",
			placeholder: "Website",
		},
	],
};
