export default {
    name: "Staff",
    generic: true,
    title: "Staff",
    titleP: "Staff",
    url: "/staff",
    fields: [
        {
            type: "select",
            name: "StaffGroupId",
            tableName: "StaffGroup.name",
            label: "Staff Group",
            placeholder: "Select Staff Group",
            loadExternal: true,
            url: "/staff-groups",
            required: true,
            inTable: true,
        },
        {
            type: "text",
            inputType: "text",
            name: "name",
            tableName: "name",
            label: "Name",
            placeholder: "Enter Name",
            required: true,
            inTable: true,
        },
        {
            type: "text",
            inputType: "email",
            name: "email",
            tableName: "email",
            label: "Email",
            placeholder: "Enter Email",
            required: true,
            inTable: true,
        },
        {
            type: "text",
            inputType: "password",
            name: "password",
            tableName: "password",
            label: "Password",
            placeholder: "Enter Password",
            required: true,
        },
        {
            type: "text",
            inputType: "text",
            name: "title",
            tableName: "title",
            label: "Title",
            placeholder: "Enter Title",
            inTable: true,
        },
        {
            type: "text",
            inputType: "number",
            name: "workingHours",
            tableName: "workingHours",
            label: "Working Hours",
            placeholder: "Enter Working Hours",
            inTable: true,
        },
        {
            type: "select",
            name: "nationality",
            tableName: "nationality",
            label: "Nationality",
            url: "/public/get-country",
            options: [],
            placeholder: "Select Nationality",
            loadExternal: true,
            isPublic: true,
        },
        {
            type: "select",
            name: "country",
            tableName: "country",
            label: "Country",
            url: "/public/get-country",
            options: [],
            placeholder: "Select Country",
            loadExternal: true,
            isPublic: true,
        },
        {
            type: "text",
            inputType: "text",
            name: "state",
            tableName: "state",
            label: "State",
            placeholder: "Enter State",
        },
        {
            type: "text",
            inputType: "text",
            name: "city",
            tableName: "city",
            label: "City",
            placeholder: "Enter City",
        },
        {
            type: "text",
            inputType: "text",
            name: "street",
            tableName: "street",
            label: "Street",
            placeholder: "Enter Street",
        },
        {
            type: "text",
            inputType: "text",
            name: "zipCode",
            tableName: "zipCode",
            label: "Zip Code",
            placeholder: "Enter Zip Code",
        },
        {
            type: "tel",
            inputType: "tel",
            name: "phone",
            tableName: "phone",
            label: "Phone",
            placeholder: "Enter Phone",
            inTable: true,
        },
        {
            type: "date",
            inputType: "date",
            name: "start",
            tableName: "start",
            label: "Start Date",
            placeholder: "Select Start Date",
            inTable: true,
        },
        {
            type: "date",
            inputType: "date",
            name: "end",
            tableName: "end",
            label: "End Date",
            placeholder: "Select End Date",
            inTable: true,
        },
        {
            type: "textarea",
            inputType: "text",
            name: "notes",
            tableName: "notes",
            label: "Notes",
            placeholder: "Enter Notes",
            inTable: true,
        },
        {
            type: "checkbox",
            inputType: "checkbox",
            name: "active",
            tableName: "active",
            label: "Active",
            placeholder: "Active",
            inTable: true,
        },
    ],
};
