import {DateFormats, TimeFormats} from "../../data/model/settings-date-time-formats";
import {numberFormats} from "../../data/model/setting-number-formats";
import {clockFormat} from "../../data/model/susoft-clock-format";

const GeneralSettings = {
	title: "User Settings",
	titleP: "User Settings",
	fields: [
		{
			type: "file",
			name: "logo",
			inputType: "file",
			label: "Company Logo",
			placeholder: "Pick a file",
			required: false,
			inTable: false,
			multiple: false
		},
		{
			type: "text",
			name: "name",
			tableName: "name",
			inputType: "text",
			label: "Name",
			placeholder: "Enter Name",
			required: true,
			inTable: true,
		},
		{
			type: "text",
			name: "email",
			tableName: "email",
			inputType: "email",
			label: "Email",
			placeholder: "Enter Email",
			required: true,
			inTable: true,
		},
		{
			type: "text",
			name: "password",
			tableName: "password",
			inputType: "password",
			label: "Password",
			placeholder: "Enter Password",
			required: true,
			inTable: true,
		},
		{
			type: "select",
			name: "currency",
			tableName: "currency",
			label: "currency",
			placeholder: "Select Currency",
			loadExternal: true,
			url: "/public/get-currency",
			isPublic: true,
			options: [],
			required: true,
			inTable: true,
		},
		{
			type: "select",
			name: "country",
			tableName: "country",
			label: "Country",
			placeholder: "Select Country",
			loadExternal: true,
			url: "/public/get-country",
			isPublic: true,
			options: [],
			required: true,
			inTable: true,
		},
		{
			type: "text",
			name: "phone",
			tableName: "phone",
			inputType: "tel",
			label: "Phone",
			placeholder: "Enter Phone",
			inTable: true,
		},
		{
			type: "select",
			name: "nationality",
			tableName: "nationality",
			label: "Nationality",
			placeholder: "Select Nationality",
			loadExternal: true,
			url: "/public/get-country",
			isPublic: true,
			options: [],
			inTable: true,
		},
		{
			type: "text",
			name: "state",
			tableName: "state",
			inputType: "text",
			label: "State",
			placeholder: "Enter State",
			inTable: true,
		},
		{
			type: "text",
			name: "city",
			tableName: "city",
			inputType: "text",
			label: "City",
			placeholder: "Enter City",
			inTable: true,
		},
		{
			type: "text",
			name: "street",
			tableName: "street",
			inputType: "text",
			label: "Street",
			placeholder: "Enter Street",
			inTable: true,
		},
		{
			type: "text",
			name: "zipCode",
			tableName: "zipCode",
			inputType: "text",
			label: "Zip Code",
			placeholder: "Enter Zip Code",
			inTable: true,
		},
		{
			type: "text",
			name: "companyName",
			tableName: "companyName",
			inputType: "text",
			label: "Company Name",
			placeholder: "Enter Company Name",
			inTable: true,
		},
		{
			type: "text",
			name: "companyPhone",
			tableName: "companyPhone",
			inputType: "tel",
			label: "Company Phone",
			placeholder: "Company Phone",
			inTable: true,
		},
		{
			type: "text",
			name: "website",
			tableName: "website",
			inputType: "url",
			label: "Website",
			placeholder: "Enter Website",
			inTable: true,
		},
		{
			type: "select",
			name: "dateFormat",
			label: "Date Format",
			placeholder: "Select Date Format",
			loadExternal: false,
			required: true,
			url: "",
			isPublic: true,
			options: DateFormats,
			inTable: true,
		},
		{
			type: "select",
			name: "timeFormat",
			label: "Time Format",
			placeholder: "Select Time Format",
			loadExternal: false,
			url: "",
			required: true,
			isPublic: true,
			options: TimeFormats,
			inTable: true
		},
		{
			type: "select",
			name: "numberFormat",
			label: "Numbers Format",
			placeholder: "Select Numbers Format",
			loadExternal: false,
			required: true,
			url: "",
			isPublic: true,
			options: numberFormats,
			inTable: true
		},
		{
			type: "select",
			name: "clockFormat",
			label: "Clock Format",
			placeholder: "Select Clock Format",
			loadExternal: false,
			required: true,
			url: "",
			isPublic: true,
			options: clockFormat,
			inTable: true
		},
		{
			type: "checkbox",
			name: "showOrganizers",
			tableName: "showOrganizers",
			inputType: "checkbox",
			label: "Show Organizers Details (In the event register page)",
			placeholder: "Show Organizers",
			inTable: true,
		},
	],
};

export { GeneralSettings };
